#
#
# Ansible role for <INSERT DESCRIPTION HERE>
#
#
#-------------------------------------------------------------------------------
# Check OS is supported
#-------------------------------------------------------------------------------
- set_fact:
    os_distribution_version: "{{ansible_distribution}}-{{ansible_distribution_major_version}}"
  tags: always

- name: "Check {{os_distribution_version}} is supported by this role"
  fail: msg="OS '{{ os_distribution_version }}' is not supported for this role"
  when: "os_distribution_version not in role_supported_os"

#-------------------------------------------------------------------------------
# Load variable from OS Specific locations
#-------------------------------------------------------------------------------
- name: Gather OS Specific Variables for {{ansible_distribution}}-{{ansible_distribution_major_version}}
  include_vars: "{{item}}"
  ignore_errors: true
  with_first_found:
    - files:
      - "../vars/vars-{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
      - "../vars/vars-{{ansible_distribution}}.yml"

#-------------------------------------------------------------------------------
# check variables
# This makes sure that all variables defined in the required_vars list are
# defined prior to starting the role tasks
#-------------------------------------------------------------------------------
- name: "Check required variables"
  fail: msg="Variable '{{item}}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"

#-------------------------------------------------------------------------------
- include_tasks: "{{file_item}}"
  with_first_found:
    - "100-drop-data/drop-data-{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "100-drop-data/drop-data-{{ansible_distribution}}.yml"
    - "100-drop-data/drop-data.yml"
  loop_control:
    loop_var: file_item
  when : (do_drop_data|bool) or (do_uninstall_all|bool)

#-------------------------------------------------------------------------------
- include_tasks: "{{file_item}}"
  with_first_found:
    - "110-uninstall-distrib/uninstall-distrib-{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "110-uninstall-distrib/uninstall-distrib-{{ansible_distribution}}.yml"
    - "110-uninstall-distrib/uninstall-distrib.yml"
  loop_control:
    loop_var: file_item
  when : (do_uninstall_distrib|bool) or (do_uninstall_all|bool)

#-------------------------------------------------------------------------------
- include_tasks: "{{file_item}}"
  with_first_found:
    - "030-configure/configure-{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "030-configure/configure-{{ansible_distribution}}.yml"
    - "030-configure/configure.yml"
  loop_control:
    loop_var: file_item
  when : (do_install|bool)

#-------------------------------------------------------------------------------
- include_tasks: "{{file_item}}"
  with_first_found:
    - "040-service/service-{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "040-service/service-{{ansible_distribution}}.yml"
    - "040-service/service.yml"
  loop_control:
    loop_var: file_item
  when : (do_install|bool)


#-------------------------------------------------------------------------------
#- include_tasks: "{{file_item}}"
#  with_first_found:
#    - "050-selinux/selinux-{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
#    - "050-selinux/selinux-{{ansible_distribution}}.yml"
#    - "050-selinux/selinux.yml"
#  loop_control:
#    loop_var: file_item
#  when : (do_install|bool)
