
#--
# This list records all variable that must be defined at role execution
required_vars:
  - do_install
  - do_uninstall_all
  - do_uninstall_distrib
  - role_supported_os
  - dependencies
  - openjdk_supported_versions
  - openjdk_version_major
  - openjdk_package
#--
# a list of supported os formated as the result of :
# {{ansible_distribution}}-{{ansible_distribution_major_version}}
#
# values for ansible_distribution (CentOS, RedHat, Debian)
#
role_supported_os:
  - CentOS-7
  - Ubuntu-18

#--
# a list of dependencies that should be installed at deps stage
dependencies:

#--
# list of major versions supported by this role
# Note: starting with version 9 and later, openjdk must be installed using the tarball
#
openjdk_supported_versions:
  - 7
  - 8
  - 11
