
#--
- name : "Ensure additionnal modules"
  file:
    src: "{{apache_config_server_root}}/mods-available/{{item}}"
    dest: "{{apache_config_server_root}}/mods-enabled/{{item}}"
    state: "link"
    owner: "root"
    group: "root"
  with_items:
    - "{{apache_config_modules}}"


- name: "Ensure additional configuration"
  template:
    src: "etc/httpd/conf.d/{{item}}"
    dest: "{{apache_config_server_root}}/sites-enabled/{{item}}"
  with_items:
    - 31-vhost-proxy.conf
    - 31-vhost-proxy-ssl.conf
