#
#
# Ansible role for firewalld
#
#
#-------------------------------------------------------------------------------
# Check OS is supported
#-------------------------------------------------------------------------------
- set_fact:
    os_distribution_version: "{{ansible_distribution}}-{{ansible_distribution_major_version}}"
  tags: always

- name: "Check {{os_distribution_version}} is supported by this role"
  fail: msg="OS '{{ os_distribution_version }}' is not supported for this role"
  when: "os_distribution_version not in role_supported_os"

#-------------------------------------------------------------------------------
# Load variable from OS Specific locations
#-------------------------------------------------------------------------------
- name: Gather OS Specific Variables for {{ansible_distribution}}-{{ansible_distribution_major_version}}
  include_vars: "{{item}}"
  ignore_errors: true
  with_first_found:
    - files:
      - "../vars/vars-{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
      - "../vars/vars-{{ansible_distribution}}.yml"      

# Note: using ansible 2.8+, remove skip parameter and replace with
# ignore_errors: true
# at same level as with_first_found

#-------------------------------------------------------------------------------
# check variables
# This makes sure that all variables defined in the required_vars list are
# defined prior to starting the role tasks
#-------------------------------------------------------------------------------
- name: "Check required variables"
  fail: msg="Variable '{{item}}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"


#-------------------------------------------------------------------------------
- include_tasks: "{{file_item}}"
  with_first_found:
    - "021-install-{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"
    - "021-install-{{ansible_distribution}}.yml"
    - "021-install.yml"
  loop_control:
    loop_var: file_item
  when : (do_install|bool)
